# This is the name of the workflow, which will be displayed in the "Actions" tab of your GitHub repository.
name: Angular CI

# This section defines when the workflow should be triggered.
on:
  # Run on pushes to the 'main' branch.
  push:
    branches: ["main"]
  # Run on any pull request that targets the 'main' branch.
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # We'll define a single job called "build-and-test".
  build-and-test:
    # The type of virtual machine to run the job on. "ubuntu-latest" is a good, standard choice.
    runs-on: ubuntu-latest

    # A job is a sequence of steps.
    steps:
      # Step 1: Check out your repository code so the workflow can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the correct version of Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a version that matches your development environment

      # Step 3: Install dependencies. "npm ci" is faster and more reliable for CI than "npm install".
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the unit tests using the script we defined in package.json.
      - name: Run unit tests
        run: npm run test:ci
